# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Startups y las Apis VI"
email: "contacta@apiaddicts.org"
description: "El evento que muestra la importancia de las APIs para las startups"
baseurl: "https://startupsylasapis.apiaddicts.org"
#baseurl: "/startupsylasapis"
url: "https://startupsylasapis.apiaddicts.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-63062484-4"
googleAnalyticsSiteUrl: "www.startupsylasapis.es"
siteVerification: "8syDqXyPBXLeDN4OObptLtn2xyRCTBo-W9lLWhkoW_A"

# Organizer Info
organizerName: "API Addicts"
organizerAlternateName: "API Addicts"
organizerDescription: "Comunidad abierta en la que tratamos con pasión todos los aspectos de una API con un enfoque 360º"
organizerEmail: "contacta@apiaddicts.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.apiaddicts.org/"

# Head
metaKeywords: "evento, api, apiaddicts, cloudappi, REST, node, .NET, meetup, developers, Madrid, startups,apigee, innovacion,"
twitterAccount: "@apiaddicts"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://forms.gle/9vpHpRug1u1gdfew5"
c4sponsorsUrl: "mailto:contacta@apiaddicts.org?subject=Colaborar%20StarupylasapisIII"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Equipo"}
 #- {permalink: "/logistics/", text: "Logistica"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 #- {link: "https://www.eventbrite.es/e/entradas-startups-y-las-apis-2021-157469817463", text: "Obtener entradas"}
rightNavigationButtons:
 #- {link: "https://www.eventbrite.es/e/entradas-startups-y-las-apis-2021-157469817463", text: "Obtener entradas"}

# Hero Block
heroImage: "portada.jpg"
heroTitle: "Startups y las APIs VI <typeout>"
eventDate: "12, 13, 14 y 15 Julio de 2021"
typeoutTextValues: '"(Startups)", "(Tecnología)", "(Negocio)", "(Innovación)"'
typeoutFallback: "(Portal de Apis)"
heroButtons:
 #- {link: "https://forms.gle/9vpHpRug1u1gdfew5", text: "Enviar propuesta"}
 #- {permalink: "/#tickets", text: "Comprar entradas"}
 - {link: "https://www.eventbrite.es/e/entradas-startups-y-las-apis-2021-157469817463", text: "Obtener entradas"}

 # About Block
aboutTitle: "Startups y las APIs"
aboutBlock:
 - {title: "Startups", image: "conference.jpg", text: "Startups dónde las APIs son muy importantes"}
 - {title: "Grandes empresas que apoyan a startups", image: "workshop.jpg", text: "Porque las startups ya no están solas"}

# Participa Block
participaTitle: "¿Quieres ser speaker?"
participaText: "Seguro que tienes grandes cosas que contar ¡queremos escucharte!"
participaButtonLink: "https://forms.gle/zzpwcjoENprtaKEh7"
participaButtonText: "Enviar mi propuesta"

# Concurso Block
concursoTitle: "Concurso para startups"
concursoText: "Si utilizas APIs en tus modelos de negocio, ¡participa!"
concursoButtonLink: "https://forms.gle/QnBTDutJunK1Zc7T9"
concursoButtonText: "¡Me interesa!"

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "5000", specialCharacter: "+", info: "APIAddicts", detail: "registrados"}
 - {count: "6", specialCharacter: "+", info: "horas", detail: "en torno a las APIs"}
 - {count: "9", specialCharacter: "+", info: "ponentes", detail: "de todo el mundo"}
# - {count: "2", specialCharacter: "", info: "tracks", detail: "Charla"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "ponencias.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Ponentes"
rockstarSpeakersButtonText: "Ver todos"

# Location Block
locationBlockTitle: "Ubicación"
eventLocationName: "Campus Madrid"
eventLocationLink: "https://www.campus.co/madrid/es"
eventStreetAddress: "Calle Moreno Nieto, 2"
eventAddressLocality: "Madrid"
eventAddressLocalityRegion: "Madrid"
eventPostalCode: "28005"
eventAddressCountry: "España"
eventStartTime: "2018-04-11T18:00"
eventDoorTime: "18:00"
eventEndTime: "2018-04-11T21:00"
eventPlaceCoordinates: "40.4125986, -3.7182459000000563"
mapCenterCoordinates: "40.4125986, -3.7182459000000563"
mapMobileCenterCoordinates: "40.4125986, -3.7182459000000563"

# Venue Block
venueBlockTitle: "Dónde"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Campus Madrid"
venueFeatures: ["Sala de conferencias", "Espacio para emprendedores", "En el centro de Madrid"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Sigue el evento"
twitterHashTag: "startupsylasapis"
twitterFeed: "http://tweetledee.cloudappi.net/searchjson_nocache.php?q=apidaysmad17"  

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Colaboradores"
partnersC4sponsorsButton: "Colaborar"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=apiaddicts", icon: "twitter"}
 - {link: "https://www.youtube.com/channel/UCepaRmZBCmbdU4QqNhSV5jQ/videos", icon: "youtube"}
 - {link: "https://facebook.com/apiaddicts", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://apiaddicts.org", text: "API Addicts"}
   - {link: "https://www.meetup.com/es-ES/preview/ApiAddicts", text: "Grupo de Meetup"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:contacta@apiaddicts.org", text: "contacta@apiaddicts.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de conducta"}

# Blog
blogTitle: "Últimas Noticias"
blogCommentsEnabled: true
discusShortName: "apiaddicts"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre Nosotros"
aboutUs: "En los últimos años, las APIs se han convertido en una forma revolucionaria de negocio para las empresas.
  El número de innovaciones tecnológicas y de industrias que están creciendo gracias al poder de las APIs es enorme.
  Cada vez se abren más puertas de negocio gracias a las APIs. <br>
  Por eso en API Addicts nos gusta compartir con la comunidad nuestra experiencia. Nos gustan las APIs en todos sus
  formatos. Somos amantes y expertos de las APIs. Así fue como creamos el grupo, por el interés de crear una comunidad abierta
  en la cual todos puedan participar y aprender acerca de las APIs. <br>
  Actualmente somos el mayor grupo hispano hablante a nivel nacional, y pronto lo seremos a nivel mundial.
  Si no nos conoces, puedes saber más sobre nosotros en nuestro y ver lo que hacemos en nuestro canal de youtube. 
  <br>
  <br>
  Las startups han demostrado ser un elemento clave en el impulso de las nuevas tecnologías y podría decirse que son el motor 
  de la transformación digital de todos los sectores. Es por ello que un año más queremos reunir a los casos de éxito más disruptivos del panoráma en un encuentro anual internacional. 
  ¡Bienvenidos al evento #StartupsylasAPIs21!
  <br>
  Organizado por la Fundación sin ánimo de lucro APIAddicts, este evento es un punto de encuentro internacional entre nuevos proyectos, casos de éxito y grandes empresas, quienes inspiran a la transformación digital a través de su experiencia con las APIs.
  Cada año este evento busca se convierte en un punto de encuentro internacional entre nuevos proyectos, casos de éxito y grandes empresas, quienes inspiran a la transformación digital a través de su experiencia con las APIs.
  Aunque las APIs son un factor clave en el éxito de las empresas actuales, es un término desconocido todavía para mucha gente. Por ello, con este evento y los meetups que realiza la Fundación y pueden verse en su canal de Youtube se pretende seguir evangelizando. 
  Como dice Marco Antonio Sanz: - Cualquier persona, aunque no sea técnica, tiene que ver que las APIs son importantes y son un nuevo modelo de negocio. 
  El evento tendrá lugar los días 13, 14 y 15 de Julio 2021 y el acceso es totalmente gratuito y online. Aunque aún quedan muchos ponentes internacionales por confirmar, los cuales se irán avisando por las Redes Sociales (link linkedin), ya se han podido descubrir algunos expertos y proyectos innovadores que tendrán cita en el encuentro de este año. Puedes verlos todos aquí (link ponentes)
  Como siempre, la temática se dividirá en 3 perspectivas. Esta vez se ha apostado por centrarse en sectores claves como son Fintech, Insurtech y HR Tech. De este modo, se pretende mostrar cómo a través de las APIs se puede impulsar la transformación digital de cualquier negocio, incluidos sectores tan tradicionales como la Banca y los Seguros.  
  ¡Te esperamos APIAddict!"
  <br>
  <br>
 - {link: "https://www.eventbrite.es/e/entradas-startups-y-las-apis-2021-157469817463", text: "Reservar mi plaza"}

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
